name: dart_pact_consumer
description: A consumer library to build and test pact contracts.
version: 1.3.0
# homepage: https://www.example.com
repository: https://github.com/pak3nuh/dart_pact_consumer/tree/main
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_serializable: 6.1.4
  json_annotation: 4.4.0

dev_dependencies:
  pedantic: 1.9.0
  test: 1.20.1
  build_runner: 2.1.7
